name: lan-vps-global

include:
  - excalidraw/docker-compose.yml
  - heimdall/docker-compose.yml
  - jellyfin/docker-compose.yml
  - minecraft-server/docker-compose.yml
  - pihole/docker-compose.yml
  - portainer/docker-compose.yml
  - uptime-kuma/docker-compose.yml